### ISSUE TITLE
Post HTML lives in 3 places

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#14]

**Comment by Martin-Alexander** [comment]
Is the issue that you want to be able to easily find and edit the HTML of post types?

**Comment by mattbischoff** [comment]
Yes, and I’d like to be able to change it in one and only one palce.

**Comment by Martin-Alexander** [comment]
I think that this is solved by

https://github.com/mattbischoff/matthewbischoff.com/pull/52

I mean, the HTML is still separated into fragments, but nothing is duplicated anymore.

**Comment by mattbischoff** [comment]
Yeah!
