### ISSUE TITLE
Timestamp spacing inside tweet posts is off

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#19]

**Comment by Martin-Alexander** [comment]
Are you referring to this spacing?

![image](https://user-images.githubusercontent.com/19353631/78734643-c59f1500-7916-11ea-8ca7-31378fdbd8f5.png)

**Comment by mattbischoff** [comment]
No. This post: https://matthewbischoff.com/john-mulaney-and-stephen-colbert-explore-each-others-deepest-anxieties/

There’s no bottom margin on the date.
