### ISSUE TITLE
Tweet post hrefs are the wrong color

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#20]

**Comment by Martin-Alexander** [comment]
Are you referring to this?

![image](https://user-images.githubusercontent.com/19353631/78734507-79ec6b80-7916-11ea-8fdc-257ec1c6384c.png)

**Comment by mattbischoff** [comment]
No, I’m referring to this:

<img width="745" alt="Screen Shot 2020-04-12 at 1 24 39 PM" src="https://user-images.githubusercontent.com/14093/79075452-fa1d2300-7cc0-11ea-8dba-71ae3380fd48.png">


Links in this post should be the brighter red.

**Comment by mattbischoff** [comment]
@Martin-Alexander this is working on the index but not permalink pages
