### ISSUE TITLE
Expose categories on posts

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#22]

**Comment by Martin-Alexander** [comment]
Do you have an idea of what this should look like. With your input I can mock something up if you'd like.

Also, clicking on the category name will link to the category page?

**Comment by mattbischoff** [comment]
> Do you have an idea of what this should look like. With your input I can mock something up if you'd like.

It should looks similar in size and weight to the date line at the bottom of the post. It should be a line of text that says:

**Filed to:** Tech, Culture • **Tagged: #generous, #brian michel**

The links should be blue (or the post color if it’s not a blue post). The rest of the text should be the same color as the date.

> Also, clicking on the category name will link to the category page?

Yes.

**Comment by Martin-Alexander** [comment]
This is done.
