### ISSUE TITLE
RSS: Want posts with a link to link out and have a way to get to the post on my site as well

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#24]

**Comment by Martin-Alexander** [comment]
Where in the RSS data do you want the link to appear (e.g.: before/after the body text). And what format do you want it in (e.g.: "Click here to read this post on my blog").

**Comment by mattbischoff** [comment]
After the body text. Just this symbol ∞ on a new line that links to the permalink on my site. Only for `link` posts.
