### ISSUE TITLE
Want a way to write custom tweet text

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#25]

**Comment by Martin-Alexander** [comment]
Hey, I know we discussed this on the video call, but I can't fine my notes.

If I remember correctly, you have an integration with twitter that automatically tweets new posts. And you want each post to have some meta-data that will determine what text will accompany the link in the tweet.

Is that correct?

**Comment by mattbischoff** [comment]
That’s right. I’d like the tweet text to be published as a custom element in the atom / rss feed and available as a `default` field on new posts.
