### ISSUE TITLE
Videos are squished

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#26]
https://matthewbischoff.com/barely-managing/

**Comment by Martin-Alexander** [comment]
In this case it looks like the `<iframe>` element is using its own CSS that specifies that width for the video element inside it. 

I can look into it more, but my current understanding is that modifying content inside an `iframe` is impossible (for security reasons). You're essentially hosting someone else's webpage inside your own and you have no control over what goes on inside there.

You can control the overall size and position of the `iframe`, but not what's inside of it. And in this case even though the `iframe` is the proper width the video element inside of it is set to be small.

**Comment by mattbischoff** [comment]
Gotcha. I’m gonna close this.
