### ISSUE TITLE
Mobile Performance

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#27]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmatthewbischoff.com&tab=mobile

**Comment by Martin-Alexander** [comment]
I didn't intentionally change anything related to performance, but when I run this lighthouse audit I'm getting a score of 98 for performance. 🤷

One thing to note is that this test will miss performance issues with infinite scrolling. It just measures initial page load, but as you keep scrolling new resources are loaded (mainly third-party assets from embedded things).

On my laptop (adblock turned off & mid-range ultrabook CPU) I get a constant 60 FPS if I just scroll down continuously with a few dropped frames when something like an embedded video or audio player loads in.

Another thing. I think at this point, performance issues are going to dominated by third-party imports. I would imagine most vendors are good about this, but you never know sometimes.

**Comment by mattbischoff** [comment]
Yeah, I think we can close this.
