### ISSUE TITLE
Time dropdown loses chevron and latest after interacting with it

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#28]

**Comment by Martin-Alexander** [comment]
I haven't been able to reproduce this.

What steps do you take to reproduce it? And does it only occur on a specific platforms (iOS, Android Chrome, Safari, Chrome, etc...)?

**Comment by mattbischoff** [comment]
Actually now I’m seeing a different bug (that I likely introduced) where the dropdown gets cut off. Can you help me figure out how I broke that?

<img width="250" alt="Screen Shot 2020-04-12 at 1 17 00 PM" src="https://user-images.githubusercontent.com/14093/79075300-f9d05800-7cbf-11ea-8eb9-0876a488b207.png">

**Comment by Martin-Alexander** [comment]
Okay, it looks like this is the result of the "Navbar scrolling into view on mobile" code h
aving been commented out.

Did you comment that out because you just don't want that little scrolling animations?

**Comment by mattbischoff** [comment]
Yes. I wanted just to turn off the scroll animation. Whoops.

**Comment by Martin-Alexander** [comment]
Do you want me to spend time trying to replicate the original bug? Might end up being a wild goose chase, but if you have some leads I can investigate from there...

**Comment by mattbischoff** [comment]
Yeah, I’ll take a look
