### ISSUE TITLE
Inline Tweets Don’t Render on Index Page but Do on Permalink Pages

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#29]
![IMG_2691](https://user-images.githubusercontent.com/14093/77261508-4a2a3c00-6c65-11ea-8089-05c63ed4363e.png)

**Comment by Martin-Alexander** [comment]
And I assume you want them to render on both the show page and index page...

**Comment by mattbischoff** [comment]
Yes.
