### ISSUE TITLE
Header description overlaps Matt in photo

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#30]
![image](https://user-images.githubusercontent.com/14093/77261593-f79d4f80-6c65-11ea-808c-fd3484f2cf04.png)

**Comment by Martin-Alexander** [comment]
To achieve this, do you want

- The font (or line height) smaller
- The header taller
- Less vertical spacing between elements

**Comment by Martin-Alexander** [comment]
If you don't know I can mock up each option and show you.

**Comment by mattbischoff** [comment]
I think slightly shorter text: cut the last sentence + a right margin should work.
