### ISSUE TITLE
Videos are not full bleed in tweet posts

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#31]
![image](https://user-images.githubusercontent.com/14093/77261601-0552d500-6c66-11ea-953c-2da5f6ee0ed4.png)

**Comment by Martin-Alexander** [comment]
I don't know what "full bleed" means.

**Comment by mattbischoff** [comment]
What I mean is that the video should stretch horizontally all the way to the edges of the purple (in this case) box. So it shouldn’t have any margins like the rest of the post content.

**Comment by Martin-Alexander** [comment]
Do you want it to be full bleed just for mobile? Because on desktop it looks like this:

![image](https://user-images.githubusercontent.com/19353631/79708512-929d3f80-828d-11ea-8de2-43fcdcedb3c6.png)

**Comment by Martin-Alexander** [comment]
Also, I'm not sure what the rules for this should be. In this case the video is just an `iframe`. I could set all `iframe`s to be full bleed, but I assume you wouldn't want non-video `iframe`s to be full bleed?

I could make a system whereby, if you want something full bleed, you would need to add some HTML attribute

Like, at the moment your markdown looks like this:

```html
<iframe loading="lazy" title="John Mulaney & Colbert on Anxiety" width="560" height="315" src="https://www.youtube.com/embed/zGf6CGBbWFU" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

This clip is what late-night TV is at its best: funny, raw, and full of things you might not say when everyone’s awake.
```

But I could make it so that to have the video full bleed you would need to add `class="full-bleed"` like so: 

```html
<iframe class="full-bleed" loading="lazy" title="John Mulaney & Colbert on Anxiety" width="560" height="315" src="https://www.youtube.com/embed/zGf6CGBbWFU" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

This clip is what late-night TV is at its best: funny, raw, and full of things you might not say when everyone’s awake.
```

**Comment by mattbischoff** [comment]
Let’s go with all iframes, video, audio, or image elements being full bleed. No attribute needed.

**Comment by Martin-Alexander** [comment]
In the case of images, I assume you will set a height, the width will just be the natural width of the tweet box (determined by the screen width) and the image will be cropped and centered accordingly

**Comment by mattbischoff** [comment]
> Do you want it to be full bleed just for mobile? Because on desktop it looks like this:

Let’s do just mobile, yes.

**Comment by mattbischoff** [comment]
> In the case of images, I assume you will set a height, the width will just be the natural width of the tweet box (determined by the screen width) and the image will be cropped and centered accordingly

I’ll likely let the image size itself, so the image should be it’s natural width if it’s smaller than the tweet box, or the full width if it’s larger, with the height determined by the aspect ratio. No images should be cropped.
