### ISSUE TITLE
Syntax Highlighted Code

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#34]

**Comment by Martin-Alexander** [comment]
Do you mean that you want to be able to put formatted code snippets in your posts that have syntax highlighting?

Like, this:

-----

Hello blog readers, blah blah blah, and then I saw something that piqued my interest:

```javascript
console.log("Hello world");
```

That was really cool!

**Comment by mattbischoff** [comment]
Exactly. I believe [Kramdown](https://kramdown.gettalong.org) which we use to render the markdown supports this fairly well out of the box, so this is mostly a task about configuring that.

**Comment by Martin-Alexander** [comment]
Is there a specific theme you want for the highlighting?

I found this one. I (or you) could tweak a few of the problematic colours if you wanna keep it

![image](https://user-images.githubusercontent.com/19353631/79708363-3803e380-828d-11ea-99d1-ce74f872e136.png)

**Comment by mattbischoff** [comment]
Yeah, I can tweak the theme
